language: android
jdk:
    - oraclejdk8

android:
    components:
        - build-tools-26.0.2
env:
    global:
        # Keep gradle from crapping all over the log
        - TERM=dumb
    matrix:
        - nodejs_version=10

node_js:
  - 5.5

notifications:
  email:
    recipients:
      - lpanjwani@outlook.com
    on_success: never # default: change
    on_failure: always # default: always

sudo: false

branches:
  only:
  - master

install:
  - nvm install $nodejs_version
  - npm cache clean --force
  - npm install
  - npm install -g cordova
  - echo y | android update sdk -u --filter android-23,android-26,android-28

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
  - exit 0  
